= John Galbreath

parents:: link:galbreath-james-1659.adoc[James Galbreath]; *Mary Nielson*
birth:: 29 MAY 1680; Campbeltown, Argyll, Scotland
death:: 1750

== Mary Mitchell

birth:: 1684; Campbeltown, Argyll, Scotland
death:: abt 1730
marriage:: 16 Mar 1707; Campbeltown, Argyll, Scotland

=== Children

link:galbreath-archibald-1708.adoc[Archibald Galbreath]:: b. 30 May 1708, m. *Martha White*.
Mary Galbreath:: b. 25 Dec. 1709.  Assumed died in early childhood.
link:galbreath-janet-1711.adoc[Janet Galbreath]:: b. 14 Oct. 1711, m. *David Ryburn*
James Galbreath:: b. 22 Mar 1713.  Assumed died in infancy.
Katharine Galbreath:: b. 8 Aug 1714
James Galbreath:: b. 11 May 1716.  Assumed died in infancy.
Patrick Galbreath:: b. 31 May 1718.
James Galbreath:: b. 28 July 1719.  Twins!
Mary Galbreath:: b. 28 July 1719.  Twins!
link:galbreath-john-1721.adoc[John Galbreath]:: b. 9 Dec 1721, m. *Agnes Langwill*.
David Galbreath:: b. 24 Nov. 1723.  Note: two records.
Samuel Galbreath:: b. 8 Aug 1725.  Note: two records.

== Katherine McCullen

=== Children

Archibald Galbreath:: b. July 1729

= Sources

* The second marriage is referenced in http://www.ralstongenealogy.com/number35kintmag.htm#start quote: "On Mary Mitchell's death John senior married Katherine McCallum who gave him one son, Archibald."  The birth is confirmed in OPR via ScotlandPeople.
