= Robert Galbreath

parents:: link:galbreath-samuel-1736.adoc[Samuel Galbreath]; *Janet McNair*
birth:: 12 Oct 1778; Campbeltown, Argyll, Scotland
death:: 19 May 1847; Neville, Clermont, Ohio, USA

== Catherine Harvie

parents:: *James Harvie*; link:katherine-galbreath-1714.adoc[Katherine Galbreath]
birth:: 29 JUL 1780; Campbeltown, Argyll, Scotland
death:: 21 JUN 1847; Neville, Clermont, Ohio, USA
marriage:: 18 Apr 1805; Campbeltown, Argyll, Scotland

=== Children
Jane Galbreath:: b. 11 Mar 1806
link:samuel-galbreath-1809.adoc[Samuel Galbreath]:: b. 22 Mar 1808.
link:galbreath-james-1809.adoc[James Galbreath]:: b. 27 Dec 1809. m. *Nancy Cole*.
Robert Galbreath:: b. 25 Feb 1812. d. 24 Aug 1842 in Clermont County.
link:galbreath-archibald-1814.adoc[Archibald Galbreath]:: b. 9 Feb 1814. bp 22 Feb 1815. m. *Eliza Rice*
John Galbreath:: b. 16 Apr 1817. m. *Jane McMath*.
link:galbreath-andrew-1819[Andrew Galbreath]:: b. 1 July 1819 in Clermont Co, Ohio, USA. m. *Elizabeth Shotwell*.
link:galbreath-harvie-1821[Harvie Galbreath]:: b. 8 Oct 1821 in Clermont County. n. *Nancy Carr Winters*.
