= John Galbraith

Provost of Campbeltown 1860-66

parents:: link:galbreath-archibald-1760.adoc[Archibald Galbreath]; *Jean Corbet*
birth:: 3 Sep 1809; Campbeltown, Argyleshire, Scotland
death:: 12 Sep 1881; Didsbury Manchester Lancashire, United Kingdom

== Mary Colvill McEwing

birth:: ; Argyll
death:: 1900
marriage:: 25 Jun 1838; Campbeltown, Argyle, Scotland

=== Children

Elizabeth Galbraith::  m. *James Nicol Fleming* 


= Sources

https://www.ancestry.com/family-tree/person/tree/3451498/person/6195109645/facts

http://www.ralstongenealogy.com/number35kintmag.htm#start

Note error in death.  Says 1861 but should be 1881
---
Perhaps the most distinguished member of the family who remained in Kintyre was John Galbraith (1809-1861) who was Provost of the Burgh from 1860 till 1866 and whose daughter married the ill-fated banker James Nicol Fleming (Magazine No. 28). He too was descended like the emigrant from John in Kilteddan and Mary Mitchell, but through their oldest son Archibald. 
---
